name: coffee
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2
  - pandas-stubs=2.2
  - matplotlib=3.8
  - matplotlib-venn=0.11
  - seaborn=0.13
  - types-seaborn=0.13
  - mypy=1.10
